language: c
sudo: required
before_install:
  #  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - export MAIN_PLATFORMS='declare -A main_platforms=( [esp8266]="esp8266:esp8266:huzzah" )'
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
#  - ln -s $PWD /usr/local/share/arduino/libraries/WiFiManager
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - git clone https://github.com/bblanchon/ArduinoJson			/usr/local/share/arduino/libraries/ArduinoJson
  - git clone https://github.com/marvinroger/async-mqtt-client  /usr/local/share/arduino/libraries/async-mqtt-client
  - git clone https://github.com/adafruit/Adafruit_FeatherOLED  /usr/local/share/arduino/libraries/Adafruit_FeatherOLED
  - git clone https://github.com/adafruit/Adafruit-GFX-Library  /usr/local/share/arduino/libraries/Adafruit_GFX_Library
  - git clone https://github.com/adafruit/Adafruit_SSD1306      /usr/local/share/arduino/libraries/Adafruit_SSD1306
  - git clone https://github.com/akaJes/AsyncPing               /usr/local/share/arduino/libraries/AsyncPing
  - git clone https://github.com/me-no-dev/ESPAsyncTCP          /usr/local/share/arduino/libraries/ESPAsyncTCP
  - git clone https://github.com/Jomelo/LCDMenuLib				/usr/local/share/arduino/libraries/LCDMenuLib
  - arduino --install-boards esp8266:esp8266
  - arduino --board esp8266:esp8266:huzzah --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs

script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - source $TRAVIS_BUILD_DIR/travis/common.sh
  - build_examples
#  - "cat $PWD/examples/AutoConnect/AutoConnect.ino"
#  - arduino -v --verbose-build --verify $PWD/examples/AutoConnect/AutoConnect.ino
#  - arduino --verify --board arduino:avr:uno $PWD/examples/IncomingCall/IncomingCall.ino
#  - arduino --verify --board arduino:avr:uno $PWD/examples/AdafruitIO_GPS/AdafruitIO_GPS.ino
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
